version: '3.8'

services:
  webapp:
    build: .
    container_name: stealallthecats
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CatDatabase;User Id=sa;Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
      - CATAPI_APIKEY=${CATAPI_TOKEN}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    depends_on:
      - sqlserver
      - minio
      - createbuckets

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    # depends_on: 
      # - migrations
      
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/imagebucket;
      /usr/bin/mc policy set public myminio/imagebucket;
      exit 0;
      "

  migrations:
    build: 
      context: .
      dockerfile: Migrations.Dockerfile
    depends_on: 
     - sqlserver
     
volumes:
  minio_data:
