version: '3.8'

services:
  webapp:
    build: .
    container_name: stealallthecats
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CatDatabase;User Id=sa;Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
      - CATAPI_APIKEY=${CATAPI_TOKEN}
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    # depends_on: 
      # - migrations

  migrations:
    build: 
      context: .
      dockerfile: Migrations.Dockerfile
    depends_on: 
     - sqlserver
